[tool.isort]
known_first_party = ["netdiff"]
default_section = "THIRDPARTY"
line_length = 88
multi_line_output = 3
use_parentheses = true
include_trailing_comma = true
force_grid_wrap = 0

[tool.coverage.run]
omit = [
    "netdiff/info.py",
    "*/tests/*",
    "*/migrations/*",
]
source = ["netdiff"]

[tool.docstrfmt]
extend_exclude = ["**/*.py"]
