name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  id-token: write

jobs:
  pypi-publish:
    name: Release Python Package on Pypi.org
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/netdiff
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
